### ISSUE TITLE
Left-margin no longer needed in Gedit 3.14.0

### ISSUE THREAD

**Issue by pachpict** [sergejx/gedit-fullscreen-margins#2]
When going fullscreen it already sets a left margin. Therefore the plugin only needs to set a right margin. Suggest commenting out line 113; "view.set_left_margin(margins)".

Ed

(Debian Stable, XFCE4, Gedit 3.14.0)

**Comment by sergejx** [comment]
Thank you for the report. I would resolve it during the weekend.

**Comment by sergejx** [comment]
It seems that Gedit sets left margin only when right margin indicator is displayed. So I also added if statement to check it.
