### ISSUE TITLE
Not working in Gedit 3.32.0, Arch Linux.

### ISSUE THREAD

**Issue by reuixiy** [sergejx/gedit-fullscreen-margins#5]
I will be very grateful if you could fix it. :smile_cat:

**Comment by sergejx** [comment]
Sorry for not answering earlier. Commit 36852ca4e008a4abb68990839517bb989d0dfb7d should fix the plugin compatibility with latest versions of Gedit.

**Comment by reuixiy** [comment]
Wow, thanks!
